development:
  adapter:  postgresql
  encoding: unicode
  host: localhost
  username: tron
  password: secret
  database: app_dev4
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: tron
  password: secret
  database: app_test4
  pool: 5